version: "3.7"

services:
    app:
        build:
            args:
                user: developer
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/php/:/usr/local/etc/php/conf.d/
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
